#!/bin/bash

source src/functions;

DATABASE="$(cat src/database)_test";

echo "Checando status do postgres..." &&
checkPostgres &&

echo "Criando banco de dados..." &&
createDatabase $DATABASE &&

echo "Executando scripts..." &&
runScripts $DATABASE;
